<?php

/**
 * Advertisement Vk Extension for Magento 2
 *
 * @author     Volodymyr Konstanchuk http://konstanchuk.com
 * @copyright  Copyright (c) 2017 The authors
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/** @var Konstanchuk\AdvertisementVk\Block\Script $block */
?>
<script type="text/javascript">
(window.Image ? (new Image()) : document.createElement('img')).src = location.protocol + '<?php echo sprintf('//vk.com/rtrg?r=%s', $block->getTargetCode()); ?>';
</script>
